### ISSUE TITLE
Will you gonna to port this to fabric and forge?

### ISSUE THREAD

**Issue by SettingDust** [anonymous123-code/quilt-bisect#5]
I think the idea of this mod is interesting. But it's too restrictive for only Quilt to use.
I think it would be nice to have a multi-platform port, what do you think?

For reference: https://github.com/SettingDust/preloading-tricks

**Comment by anonymous123-code** [comment]
Since Quilt supports most fabric mods, I disagree on your point that it's too restrictive.

Even if that weren't the case, Quilt loader is the only one with a nice API I can use to implement it afaik (And since preloading-tricks exists I assume its the only one). Even preloading-tricks doesn't support all the features I use, because I make mods optional instead of completely unloading them. I built bisect to work well with quilt loader and designed it to make a good use of its APIs.

Finally, I also don't want to support forge and fabric, so I probably wouldn't go multiloader (or switch) even if there was an API in the other loaders.

**Comment by SettingDust** [comment]
I'm going to implement on the other loaders from scratch someday. Is it allowed to refer to your code?

**Comment by pizzav-xyz** [comment]
> I'm going to implement on the other loaders from scratch someday. Is it allowed to refer to your code?

@SettingDust have you started this?

**Comment by SettingDust** [comment]
Totally forgot. Noop. Since the project is ARR. I'm thinking the logic by myself. 
What's I've tried is making mod sets from my mod https://github.com/SettingDust/ModSets working in the super early (It's only fro ingame now). Abandoned for it's not worth to refactor the Mod Sets.
I planning to start from zero. But havn't started XD

**Comment by pizzav-xyz** [comment]
@SettingDust have you started?
